global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-hashicorp-vault
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  reporting: true
tests:
  test1:
    parameter_input: quickstart-hashicorp-vault-exampleparams1.json
    template_file: quickstart-hashicorp-vault-example1.template
  test2:
    parameter_input: quickstart-hashicorp-vault-exampleparams2.json
    template_file: quickstart-hashicorp-vault-example2.template
